In [1]:
#1)Display “Hello World” in your output screen.
print("hello world")

hello world


In [1]:
#2)Get the input from the user and perform addition of two numbers
a=int(input("enter value of a:")) 
b=int(input("enter value of b:"))
c=a+b
print("sum is:",c)

enter value of a:4
enter value of b:8
sum is: 12


In [1]:
#3)swap two variables without temp variable
a=4
b=8
print("before swaping value is",a,b)
a=a+b
b=a-b
a=a-b
print("after swaping value is",a,b)

before swaping value is 4 8
after swaping value is 8 4


In [41]:
#4)convert the entered kilometres ( Convertion  Factor= 0.621371)
km=int(input("enter the kilometre:"))
m=km*1000
print(m)

enter the kilometre:5
5000


In [44]:
#5)check whether the given number is positive, negative or 0
a=int(input("enter the number:"))
if(a>0):
    print("positive number")
elif(a<0):
    print("negative number")
else:
        print("zero")

enter the number:4
positive number


In [5]:
#6)verify that the given year is a leap year
a=int(input("enter the year:"))
if(a%4==0):
    print("it is leap year")
else:
    print("not a leap year")

enter the year:2008
it is leap year


In [43]:
#7)display the prime numbers within the given interval
a=int(input("enter the min:"))
b=int(input("enter the max:"))
print("prime number between ",a,"to",b,"max" )
for num in range(a,b+1):
 if num>1:
        for i in range(2,num):
            if(num%i==0):
                break
        else:
            print(num)
  

enter the min:1
enter the max:10
prime number between  1 to 10 max
2
3
5
7


In [45]:
#8) display the Fibonacci sequence up to n-th term
n=int(input("enter the number:"))
a=0
b=1
c=a+b
for i in range(1,n+1):
    print(c)
    a=b
    b=c
    c=a+b

enter the number:8
1
2
3
5
8
13
21
34


In [51]:
#9) check if the number is an Armstrong number or not
num=int(input("enter the values:"))
sum=0 
ori=num
while(ori>0):
    a=ori%10
    sum+=a**3
    ori//=10
if(num==sum):
    print("amstrong number")
else:
    print("not an amstrong number")
    

enter the values:153
amstrong number


In [50]:
#10) Find the Sum of natural numbers up to n-th term
a=int(input("enter the number:"))
sum=0
for i in range(1,a+1):
 sum=sum+i
print(sum)

enter the number:5
15


In [48]:
#11)Write a function called show_stars(rows). If rows are 5, it should print the following
n = int(input("Enter the number of rows"))  
for i in range(0, n):    
        for j in range(0, i + 1):    
            print("*", end="")  
        print()  

Enter the number of rows5
*
**
***
****
*****


In [5]:
#12)Write a program to remove characters from a string starting from zero up to n and return a new string.
ini_string1 = 'Python_Programming'
n = 7
print("Initial String", ini_string1)
 # Removing n characters from string using Naive method
res = ''
for i in range(0, len(ini_string1)):
    if i >= n:
        res = res + ini_string1[i]
print("Resultant String", res)

Initial String Python_Programming
Resultant String Programming


In [20]:
#13)Iterate the given list of numbers and print only those numbers which are divisible by 5
list1=[5,12,14,18,20,25,10]
for i in list1:
    if(i%5==0):
        print(i)

5
20
25
10


In [21]:
#14) Write a program to find how many times substring “Hi” appears in the given string.
s = 'hihihhihi'
sb = 'hi'
results = 0
sub_len = len(sb)
for i in range(len(s)):
    if s[i:i+sub_len] == sb:
        results += 1
print(results)

4


In [26]:
"""15)Print the following pattern
1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5"""
rows =6
for i in range(rows):
    for j in range(i):
         print(i,end=' ')
    print('')


1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [29]:
#16)Write a program to check if the given number is a palindrome number.
n=int(input("Enter number:"))
temp=n
rev=0
while(n>0):
    dig=n%10
    rev=rev*10+dig
    n=n//10
if(temp==rev):
    print("The number is palindrome!")
else:
    print("The number not a palindrome!")

Enter number:121
The number is palindrome!


In [32]:
#17)Python program to interchange first and last elements in a list
def swapList(newList):
    size = len(newList)
    temp = newList[0]
    newList[0] = newList[size - 1]
    newList[size - 1] = temp
    return newList
newList = [12, 35, 9, 56, 24]
print(swapList(newList))

[24, 35, 9, 56, 12]


In [34]:
#18)Python program to swap two elements in a list
list1=[23,64,34,13,45,75]
pos1=int(input("enter first position:"))
pos2=int(input("enter second position:"))
list1[pos1],list1[pos2]=list1[pos2],list1[pos1]
print(list1)

enter first position:2
enter second position:3
[23, 64, 13, 34, 45, 75]


In [36]:
#19)Python Ways to find length of list
list = [10,20,30,40,50]
n = len(list)
print("The length of list is:",n)


The length of list is: 5


In [39]:
#20)Maximum of two numbers in Python
def maximum(a, b):
     if a >= b:
        return a
     else:
        return b
a = 2
b = 4
print(maximum(a, b))

4


In [40]:
#21)Minimum of two numbers in python
def maximum(a, b):
     if a <= b:
        return a
     else:
        return b
a = 2
b = 4
print(maximum(a, b))

2


In [49]:
#22)Python program to check whether the string is Symmetrical or Palindrome
string="peep"
half=int(len(string)/2)
fs=string[:half]
ss=string[half:]
if fs==ss:
    print("symmetrical")
else:
    print("Not symmetrical")
if(string==string[::-1]):
       print("palindrome")
else:
       print("not a palindrome")

Not symmetrical
palindrome


In [50]:
#23)Reverse words in a given String in Python
string = "geeks quiz practice code"
s = string.split()[::-1]
l = []
for i in s:
    l.append(i)
print(" ".join(l))


code practice quiz geeks


In [2]:
#24)Ways to remove i’th character from string in Python
test_str = "GeeksForGeeks"
new_str = ""
for i in range(len(test_str)):
    if i != 2:
        new_str = new_str + test_str[i]
print ("The string after removal of i'th character : " + new_str)

The string after removal of i'th character : GeksForGeeks


In [4]:
#25)Find length of a string in python 
str = "geeks for geeks"
print(len(str))

15


In [7]:
#26)Python program to print even length words in a string
n="This is a python language"
s=n.split(" ")
for i in s:
  if len(i)%2==0:
    print(i)

This
is
python
language


In [9]:
#27)Python program to Find the size of a Tuple
a = ("programming","python", "language")
b = ("python", "Coding") 
print("Size of the tuple is", len(a))
print("Size of the tuple is", len(b))

Size of the tuple is 3
Size of the tuple is 2


In [30]:
#28)Python – Maximum and Minimum K elements in Tuple
my_tuple = (7, 25, 36, 9, 6, 8)
print("The tuple is : ")
print(my_tuple)
K = 2
print("The value of K has been initialized to ")
print(K)
my_result = []
my_tuple = list(my_tuple)
temp = sorted(my_tuple)
for idx, val in enumerate(temp):
   if idx < K or idx >= len(temp) - K:
      my_result.append(val)
my_result = tuple(my_result)
print("The result is : " )
print(my_result)

The tuple is : 
(7, 25, 36, 9, 6, 8)
The value of K has been initialized to 
2
The result is : 
(6, 7, 25, 36)


In [31]:
#29)Python – Sum of tuple elements
def summation(test_tup):
    test = list(test_tup)
    count = 0
    for i in test:
        count += i
    return count
test_tup = (5, 20, 3, 7, 6, 8)
print(summation(test_tup))

49


In [4]:
#30)Python – Row-wise element Addition in Tuple Matrix
tupMat = [[(7, 2, 6), (4, 1, 5)], [(9, 2, 6), (4, 5, 3)]]
additionVals = [3, 2]
print("Elements of Tuple matrix initially :" + str(tupMat))
addTupMat = [[sub + (additionVals[i], ) for sub in ele] for i, ele in enumerate(tupMat)]
print("Elements of Tuple matrix after addition :" + str(addTupMat))

Elements of Tuple matrix initially :[[(7, 2, 6), (4, 1, 5)], [(9, 2, 6), (4, 5, 3)]]
Elements of Tuple matrix after addition :[[(7, 2, 6, 3), (4, 1, 5, 3)], [(9, 2, 6, 2), (4, 5, 3, 2)]]


In [1]:
#31)Create a list of tuples from given list having number and its cube in each tuple
list1 = [1, 2, 5, 6]
res = [(val, pow(val, 3)) for val in list1]
print(res)

[(1, 1), (2, 8), (5, 125), (6, 216)]


In [5]:
#32)Sort Python Dictionaries by Key or Value
myDict = {'vidh':10 ,'pavi':10 ,'suba':15 ,'apar':12 ,'anand':32}
myKeys = list(myDict.keys())
myKeys.sort()
sorted_dict = {i: myDict[i] for i in myKeys}
print(sorted_dict)

{'anand': 32, 'apar': 12, 'pavi': 10, 'suba': 15, 'vidh': 10}


In [1]:
#33.Python dictionary with keys having multiple inputs
places = {("19.07'53.2", "72.54'51.0"):"Mumbai", \
 ("28.33'34.1", "77.06'16.6"):"Delhi"}
print(places)
print('\n')
lat = []
long = []
plc = []
for i in places:
 lat.append(i[0])
 long.append(i[1])
 plc.append(places[i[0], i[1]])
print(lat)
print(long)
print(plc)

{("19.07'53.2", "72.54'51.0"): 'Mumbai', ("28.33'34.1", "77.06'16.6"): 'Delhi'}


["19.07'53.2", "28.33'34.1"]
["72.54'51.0", "77.06'16.6"]
['Mumbai', 'Delhi']


In [2]:
#34.Python program to find the sum of all items in a dictionary
dict = {'a': 100, 'b': 200, 'c': 300}
list=[]
for i in dict:
 list.append(dict[i])
final=sum(list)
print("Sum :",final)

Sum : 600


In [3]:
#35.Python program to find the length of a dictionary
dict1 ={'Name':'Steve', 'Age':30, 'Designation':'Programmer'}
print("Dictionary:", dict1)
print("Length of dictionary:", len(dict1))


Dictionary: {'Name': 'Steve', 'Age': 30, 'Designation': 'Programmer'}
Length of dictionary: 3


In [4]:
#36.Find the length of a set in python
set1=set()
set1.add(8)
set1.add(9)
set1.add((6,7))
print("Length=",len(set1))

Length= 3


In [5]:
#37.Iterate over a set in python
test_set = set("geEks")
for val in test_set:
 print(val)

E
s
g
e
k


In [6]:
#38.Maximum and Minimum in a Set
sets=set([8,16,24,1,25,3,10,65,55])
print(max(sets))
print(min(sets))

65
1


In [8]:
#39.Remove items from set
def Remove(initial_set):
 while initial_set:
     initial_set.pop()
     print(initial_set)
initial_set = set([12, 10, 13, 15, 8, 9])
Remove(initial_set)


{9, 10, 12, 13, 15}
{10, 12, 13, 15}
{12, 13, 15}
{13, 15}
{15}
set()


In [10]:
#40.Check if two lists have atleast one element common
def common_member(a, b):
 a_set = set(a)
 b_set = set(b)
 if (a_set & b_set):
    return True
 else:
    return False
a = [1, 2, 3, 4, 5]
b = [5, 6, 7, 8, 9]
print(common_member(a, b))
a =[1, 2, 3, 4, 5]
b =[6, 7, 8, 9]
print(common_member(a, b))

True
False


In [11]:
#41.Python – Assigning Subsequent Rows to Matrix first row elements
test_list = [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
print("The original list : " + str(test_list))
a=test_list[0]
b=test_list[1:len(test_list)]
d=dict()
for i in range(0,len(a)):
 d[a[i]]=b[i]
print("The Assigned Matrix : " + str(d))

The original list : [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
The Assigned Matrix : {5: [2, 0, 9], 8: [5, 4, 2], 9: [2, 3, 9]}


In [1]:
#42.Adding Matrices in Python
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


In [2]:
#43.Subtracting Matrices in Python
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
print("Subtraction of two matrix")
print(np.subtract(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


In [3]:
#44.Group similar elements into Matrix
from itertools import groupby
test_list = [1, 3, 5, 1, 3, 2, 5, 4, 2]
print("The original list : " + str(test_list))
res = [list(val) for key, val in groupby(sorted(test_list))]
print("Matrix after grouping : " + str(res))


The original list : [1, 3, 5, 1, 3, 2, 5, 4, 2]
Matrix after grouping : [[1, 1], [2, 2], [3, 3], [4], [5, 5]]


In [5]:
#45.Create an n x n square matrix, where all the sub-matrix has the sum of opposite corner elements as even
import itertools
def sub_mat_even(n):
    temp = itertools.count(1)
    l = [[next(temp)for i in range(n)]for i in range(n)]
    if n%2 == 0:
        for i in range(0,len(l)):
            if i%2 == 1:
                l[i][:] = l[i][::-1]
    for i in range(n):
        for j in range(n):                  
            print(l[i][j],end=" ")
        print()
n = 4
sub_mat_even(n)


1 2 3 4 
8 7 6 5 
9 10 11 12 
16 15 14 13 


In [6]:
#46.How to get list of parameters name from a function in Python
import inspect
import collections
print(inspect.signature(collections.Counter))


(iterable=None, /, **kwds)


In [7]:
#47.How to Print Multiple Arguments in Python
def GFG(name, num):
 print("Hello from ", name + ', ' + num)
GFG("geeks for geeks", "25")


Hello from  geeks for geeks, 25


In [8]:
#48.Python program to find the power of a number using recursion
def power(N, P):
    if P == 0:
        return 1
    return (N*power(N, P-1))
if __name__ == '__main__':
    N = 5
    P = 2
    print(power(N, P))

25


In [9]:
#49.Sorting objects of user defined class in Python
class GFG:
    def __init__(self, a, b):
        self.a = a 
        self.b = b
    def __repr__(self):
        return str((self.a, self.b))
gfg = [GFG("geeks", 1),
    GFG("computer", 3),
    GFG("for", 2),
    GFG("geeks", 4),
    GFG("science", 3)]
print(sorted(gfg, key=lambda x: x.b))

[('geeks', 1), ('for', 2), ('computer', 3), ('science', 3), ('geeks', 4)]


In [10]:
#50.Functions that accept variable length key value pair as arguments
def printKwargs(**kwargs):
    print(kwargs)
if __name__ == "__main__":
     printKwargs(Argument_1='gfg', Argument_2='GFG')

{'Argument_1': 'gfg', 'Argument_2': 'GFG'}
